Merge branch development to branch master
karine2711/homework pull request #1
Opened 2020-01-13 11:15 UTC by karine2711

2020-01-14 07:37 UTC, DiannaAsatryan requested changes
Karine jan pls make it simple, with static initialization of your objects and use Exception Handlings, and Bilder correctly, then I will do one more review

2020-01-14 07:37 UTC, DiannaAsatryan commented on src/exception/DefaultHandler.java
> +                    new Student.StudentBuilder("Pamela Norton", "Data Structures",
Builder pattern used incorrectly, see this post: 
https://dzone.com/articles/design-patterns-the-builder-pattern
The idea is to have many optional fields which you will give to Builder with separate method then build your original object in builder

2020-01-14 07:37 UTC, DiannaAsatryan commented on src/exception/CourseGrade.java
> +package exception;
change package name to be task name like : 'university'

2020-01-14 07:37 UTC, DiannaAsatryan commented on src/exception/DynamicArray.java
> +public class DynamicArray {
It is not right to have a common class that works with most of your classes, and I see it is out of scope for this task to dynamically increase or decrease students,Faculty, Groups.  ... .You can just create static one, or initialize it in main and use after that.
If you need to have a class which does dynamic array length changes, you should just have DynamicArray<T> and have methods (non static) to work with T type, Like it done in ArrayList

2020-01-14 07:37 UTC, DiannaAsatryan commented on src/exception/Student.java
> +            System.out.println("The grade must be in the range (0,10]. Given grade " + grade);
Solution is very complicated, and when I run it throws NulPointerException  after many tries to exit from dynamic creation process, pls change just to have static initialized objects , and I don't see Exception handling at all, for example in his case it is expected to throw some custom created exception without doing sout, and catch it in caller method

2020-01-14 07:37 UTC, DiannaAsatryan commented on src/exception/Main.java
> +        } catch (NullPointerException e) {
Don't catch NullPointerException, then create your own Exception which will extend RunTimeException and throw it getStudentByInfo(..) method like NoStudentException

2020-01-14 07:37 UTC, DiannaAsatryan commented on src/exception/DefaultHandler.java
> +    private static int i = 0;
not good to have fields which you can't guess what they are doing

2020-01-14 11:43 UTC, karine2711 commented on src/exception/DefaultHandler.java
> +                    new Student.StudentBuilder("Pamela Norton", "Data Structures",
Could you please give a hint what exactly can be changed here?

2020-01-16 11:23 UTC, DiannaAsatryan commented on src/university/Main.java
> +                System.out.println("No one in the group passes the given course, or the students were not graded!");
Karine  jan you have different splited codes by logic, why don't move each part to some small methods , for example: 
void printMinGradeOfGroupForSubject(University university, String groupName, String subject){
try {
            System.out.println("------------------------------------------------------");
            System.out.println("--Count mean grade in a given group, for a given subject--");
            Group group = UniversityService.getGroupByInfo(university, groupName,  subject);
            double grade = group.countMeanGrade("Music");
            if (grade == 0) {
                System.out.println("No one in the group passes the given course, or the students were not graded!");
 
} else {
                System.out.println("Mean grade for given subject in group "
                        + group.getName()
                        + " = " + grade
                );
            }
        } catch (ItemNotFoundException e) {
            System.out.println(e.toString());
        } catch (NullListException e) {
            e.printStackTrace();
        }
 

and the same for other parts

2020-01-16 11:23 UTC, DiannaAsatryan commented on src/university/exceptions/GradeOutOfRangeException.java
> +        return "Grade Out Of Range! Grade must be in range (" +
as I understand you learned to create exceptions by overriding toString() in class, but what I will suggest calling a constructor att creation time and providing some message to it like :
 public GradeOutOfRangeException(double grade,int minGrade,int maxGrade){
super(String.format("Grade Out Of Range! Grade must be in range [%s,%s]       Given grade %s",minGrade,maxGrade,grade));
    }

 @Override
    public String toString() {
this.getMessage();
}

as in most of the cases when you use logger, we use e.getMessage()

2020-01-16 11:23 UTC, DiannaAsatryan commented on src/university/universityParts/University.java
> +    private String[] facultyNames;
Karine jan don't store  facultyNames in class if you calculate them each time with getFacultyNames(..) method

2020-01-16 11:23 UTC, DiannaAsatryan commented on src/university/universityParts/University.java
> + * University is a singletone class, as the program is written for a specific university.
Karine jan your University is not singleton class as you have public constructor, remove these docs or make it singleton

2020-01-16 11:23 UTC, DiannaAsatryan commented on src/university/universityParts/Student.java
> +        this.fullName = student.fullName;
builder pattern used incorrectly, the idea is to fill all Student's fields from builder

2020-01-16 11:23 UTC, DiannaAsatryan commented on src/university/exceptions/nullListExceptions/NullCourseListException.java
> +    public NullCourseListException(String studentName) {
it is good that you used inheritance here

2020-01-17 08:29 UTC, DiannaAsatryan approved these changes
well done Karine jan , you can merge it

2020-01-17 12:13 UTC, merged